from typing import TypedDict, Annotated

from dotenv import load_dotenv

from langgraph.graph import StateGraph, START, END
from langgraph.graph.message import add_messages
from langgraph.prebuilt import ToolNode

from langchain_mistralai import ChatMistralAI
from langchain_community.tools.tavily_search import TavilySearchResults


load_dotenv()


# ============================================================
# TOOLS
# ============================================================

search_tool = TavilySearchResults(max_results=3)
tools = [search_tool]


# ============================================================
# LLMs
# ============================================================

reviewer_llm = ChatMistralAI(
    model="mistral-small-latest"
)

reviewer_llm_with_tools = reviewer_llm.bind_tools(tools)

critic_llm = ChatMistralAI(
    model="mistral-medium-latest"
)


# ============================================================
# STATE
# ============================================================

class State(TypedDict):
    code: str
    messages: Annotated[list, add_messages]
    review: str
    feedback: str
    approved: bool
    attempt: int


# ============================================================
# REVIEWER PROMPT
# ============================================================

REVIEWER_SYSTEM_PROMPT = """

You are an expert Python code reviewer.

Your job is to review the code provided by the user and identify
real problems, bugs, security issues, bad practices, and possible
improvements.

For every important issue, explain:

1. Issue:
   What is wrong?

2. Why it matters:
   Explain the impact in simple terms.

3. Suggested fix:
   Explain how the developer could improve it.

4. Severity:
   Low, Medium, or High.

If the question requires up-to-date information about a library,
framework, API, or Python feature, use the available web search
tool before completing the review.

Do not invent problems. Only mention issues that are actually
supported by the code or reliable information.

Return a clear, structured code review.

"""


# ============================================================
# REVIEWER NODE
# ============================================================

def reviewer_node(state: State) -> dict:
    """Reviews the given Python code."""

    code = state["code"]
    current_attempt = state.get("attempt", 0)
    existing_messages = state.get("messages", [])

    # --------------------------------------------------------
    # Tool result has just been returned.
    # Send the complete conversation back to the reviewer.
    # --------------------------------------------------------

    if existing_messages and existing_messages[-1].type == "tool":

        messages = [
            ("system", REVIEWER_SYSTEM_PROMPT),
            *existing_messages,
        ]

        response = reviewer_llm_with_tools.invoke(messages)

        return {
            "messages": [response]
        }

    # --------------------------------------------------------
    # Starting a new review attempt
    # --------------------------------------------------------

    attempt = current_attempt + 1

    previous_feedback = state.get("feedback", "")

    if attempt == 1:

        user_message = (
            f"Review this Python code:\n\n"
            f"{code}\n\n"
            f"If current information is required, use the web "
            f"search tool first."
        )

    else:

        user_message = (
            f"Improve your previous code review.\n\n"

            f"ORIGINAL CODE:\n"
            f"{code}\n\n"

            f"PREVIOUS REVIEW:\n"
            f"{state.get('review', '')}\n\n"

            f"CRITIC FEEDBACK:\n"
            f"{previous_feedback}\n\n"

            f"Rewrite the review and fix every issue identified "
            f"by the critic.\n"
            f"Do not repeat the same mistakes."
        )

    messages = [
        ("system", REVIEWER_SYSTEM_PROMPT),
        *existing_messages,
        ("human", user_message),
    ]

    response = reviewer_llm_with_tools.invoke(messages)

    return {
        "messages": [response],
        "attempt": attempt,
    }


# ============================================================
# TOOL NODE
# ============================================================

tool_node = ToolNode(tools)


# ============================================================
# EXTRACT REVIEW NODE
# ============================================================

def extract_review_node(state: State) -> dict:
    """Extracts the final review generated by the reviewer."""

    latest_message = state["messages"][-1]

    review = latest_message.content

    return {
        "review": review
    }


# ============================================================
# CRITIC PROMPT
# ============================================================

CRITIC_SYSTEM_PROMPT = """

You are a strict and accurate reviewer of AI-generated Python
code reviews.

Your job is to evaluate whether the generated code review is
accurate, useful, complete, and supported by the original code.

Check the review carefully for:

1. Accuracy
   - Does every identified issue actually exist in the code?
   - Are there any technically incorrect claims?

2. Completeness
   - Did the reviewer miss any important bugs, security issues,
     or significant problems?

3. Explanations
   - Are the explanations technically correct and easy to
     understand?

4. Suggested fixes
   - Are the suggested fixes reasonable and technically
     appropriate?

5. Severity
   - Are Low, Medium, and High severity levels appropriate?

6. Unsupported claims
   - Did the reviewer invent or assume anything that cannot be
     supported by the provided code or reliable information?

If the review is accurate, useful, and complete enough, approve it.

If the review has important problems, reject it and explain exactly
what needs to be improved.

Respond EXACTLY in this format:

VERDICT: APPROVED
FEEDBACK: <brief explanation of why the review is good>

OR

VERDICT: REJECTED
FEEDBACK: <specific problems that the reviewer needs to fix>

"""


# ============================================================
# CRITIC NODE
# ============================================================

def critic_node(state: State) -> dict:
    """Evaluates the review generated by the reviewer."""

    code = state["code"]
    review = state["review"]

    prompt = f"""
Evaluate the following AI-generated code review.

ORIGINAL PYTHON CODE:
{code}

AI-GENERATED CODE REVIEW:
{review}

Determine whether the review is accurate, useful, and complete.

If it is good enough, approve it.

If it needs improvement, reject it and provide specific feedback
that the reviewer can use to create a better review.
"""

    response = critic_llm.invoke(
        [
            ("system", CRITIC_SYSTEM_PROMPT),
            ("human", prompt)
        ]
    )

    response_text = response.content.strip()

    # --------------------------------------------------------
    # Extract verdict
    # --------------------------------------------------------

    verdict_part = response_text.upper().split(
        "FEEDBACK:",
        1
    )[0]

    is_approved = "VERDICT: APPROVED" in verdict_part

    # --------------------------------------------------------
    # Extract feedback
    # --------------------------------------------------------

    if "FEEDBACK:" in response_text:

        feedback = response_text.split(
            "FEEDBACK:",
            1
        )[1].strip()

    else:

        feedback = response_text

    verdict = "APPROVED" if is_approved else "REJECTED"

    print(f"\n[Critic Verdict: {verdict}]")
    print(f"[Critic Feedback: {feedback}]\n")

    return {
        "feedback": feedback,
        "approved": is_approved
    }


# ============================================================
# ROUTER 1 — TOOL DECISION
# ============================================================

def should_use_tool(state: State):
    """Checks whether the reviewer requested a tool."""

    last_message = state["messages"][-1]

    if getattr(last_message, "tool_calls", None):
        return "tools"

    return "extract_review"


# ============================================================
# ROUTER 2 — CRITIC DECISION
# ============================================================

def should_stop_looping(state: State):
    """Decides whether the review is finished or should be
    rewritten again."""

    # --------------------------------------------------------
    # Review approved
    # --------------------------------------------------------

    if state["approved"]:

        print("\nReview of the given code was approved.")

        return END

    # --------------------------------------------------------
    # Maximum attempts reached
    # --------------------------------------------------------

    if state["attempt"] >= 3:

        print("\nReached maximum attempts.")

        return END

    # --------------------------------------------------------
    # Review rejected → send feedback to reviewer
    # --------------------------------------------------------

    print("\nSending critic feedback back to the reviewer.")

    return "reviewer"


# ============================================================
# BUILD GRAPH
# ============================================================

graph = StateGraph(State)


# ------------------------------------------------------------
# Add nodes
# ------------------------------------------------------------

graph.add_node(
    "reviewer",
    reviewer_node
)

graph.add_node(
    "tools",
    tool_node
)

graph.add_node(
    "extract_review",
    extract_review_node
)

graph.add_node(
    "critic",
    critic_node
)


# ------------------------------------------------------------
# START → REVIEWER
# ------------------------------------------------------------

graph.add_edge(
    START,
    "reviewer"
)


# ------------------------------------------------------------
# REVIEWER → TOOLS OR EXTRACT REVIEW
# ------------------------------------------------------------

graph.add_conditional_edges(
    "reviewer",
    should_use_tool,
    {
        "tools": "tools",
        "extract_review": "extract_review",
    }
)


# ------------------------------------------------------------
# TOOLS → REVIEWER
# ------------------------------------------------------------

graph.add_edge(
    "tools",
    "reviewer"
)


# ------------------------------------------------------------
# EXTRACT REVIEW → CRITIC
# ------------------------------------------------------------

graph.add_edge(
    "extract_review",
    "critic"
)


# ------------------------------------------------------------
# CRITIC → REVIEWER OR END
# ------------------------------------------------------------

graph.add_conditional_edges(
    "critic",
    should_stop_looping,
    {
        "reviewer": "reviewer",
        END: END,
    }
)


# ============================================================
# COMPILE GRAPH
# ============================================================

app = graph.compile()


# ============================================================
# USER INPUT LOOP
# ============================================================

while True:

    print("\n" + "=" * 60)
    print("              AI CODE REVIEW AGENT")
    print("=" * 60)

    print("Paste your Python code below.")
    print("Type END on a new line when you are finished.")
    print("Type EXIT to quit.\n")

    code_lines = []

    # --------------------------------------------------------
    # Read multiline code
    # --------------------------------------------------------

    while True:

        line = input()

        if line.strip().upper() == "EXIT":

            print(
                "\nExiting AI Code Review Agent. Goodbye!"
            )

            raise SystemExit

        if line.strip().upper() == "END":

            break

        code_lines.append(line)

    code = "\n".join(code_lines).strip()

    # --------------------------------------------------------
    # Empty input
    # --------------------------------------------------------

    if not code:

        print(
            "\nNo code was provided. Please try again."
        )

        continue

    # --------------------------------------------------------
    # Start review
    # --------------------------------------------------------

    print("\n" + "-" * 60)
    print("Reviewing your code...")
    print("-" * 60)

    initial_state = {
        "code": code,
        "messages": [],
        "review": "",
        "feedback": "",
        "approved": False,
        "attempt": 0,
    }

    result = app.invoke(initial_state)

    # ========================================================
    # FINAL OUTPUT
    # ========================================================

    print("\n" + "=" * 60)
    print("                    FINAL REVIEW")
    print("=" * 60)

    print(result["review"])

    print("\n" + "=" * 60)
    print("                 CRITIC FEEDBACK")
    print("=" * 60)

    print(result["feedback"])

    print("\n" + "=" * 60)
    print("                       RESULT")
    print("=" * 60)

    print(f"Approved : {result['approved']}")
    print(f"Attempts : {result['attempt']}")

    print("=" * 60)

    # --------------------------------------------------------
    # Review another snippet?
    # --------------------------------------------------------

    choice = input(
        "\nReview another code snippet? (y/n): "
    ).strip().lower()

    if choice not in {"y", "yes"}:

        print(
            "\nExiting AI Code Review Agent. Goodbye!"
        )

        break